@startuml minesweeper_room

skinparam {

    DefaultFontColor White
    DefaultFontName Monospace
    DefaultFontSize 16
    DefaultBorderColor White
    ArrowColor Gray

    BackgroundColor Black
    BorderColor Gray
    FontColor White

    class {
        BackgroundColor Black
        BorderColor Gray
    }

    package {
        BackgroundColor Black
        BorderColor Gray
    }

}

package minesweeper_room {

    class Player {

        - _name: str
        - _leave_callbacks: Callable[[Player], None]
        - _right_click_callback: Callable[[Player, Position], None]
        - _left_click_callback: Callable[[Player, Position], None]

        + __init__(name: str)
        + name() -> str
        + leave_room() -> None
        + right_click(position: Position) -> None
        + left_click(position: Position) -> None
        + to_dict() -> Dict[str, str]
        + set_leave_callback(callback: Callable[[Player], None]) -> None
        + set_right_click_callback(callback: Callable[[Player, Position], None]) -> None
        + set_left_click_callback(callback: Callable[[Player, Position], None]) -> None
        # standard_callback(*_) -> None

    }

    class GameOptions {

        - _mines: int
        - _width: int
        - _height: int

        + __init__(mines: int, width: int, height: int)
        + mines() -> int
        + width() -> int
        + height() -> int
        + to_dict() -> Dict[str, int]

    }

    class Room {

        - _players: List[Player]
        - _board: Optional[Board]
        - _options: GameOptions
        - _room_id: str

        + __init__(options: GameOptions)
        + add_player(player: Player) -> None
        + remove_player(player: Player) -> None
        + update_options(options: GameOptions) -> None
        + start_game() -> None
        + is_won() -> bool
        + is_lost() -> bool
        + get_show_board() -> ShowBoard

    }

    Room *-- Player
    Room *-- GameOptions

}

@enduml
