from __future__ import annotations
from typing import Protocol, runtime_checkable


@runtime_checkable
class Cell(Protocol):

    def is_mine(self) -> bool: ...

    def is_flagged(self) -> bool: ...

    def is_revealed(self) -> bool: ...

    def unwrap(self) -> Cell: ...

    def flagged(self) -> Cell: ...

    def revealed(self) -> Cell: ...

    def __str__(self) -> str: ...
